In [1]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("C:\\Users\\Admin\\Downloads\\Forest_fire.csv")

In [12]:
data.head()

        Area  Oxygen  Temperature  Humidity  Fire Occurrence
0   Jharkand      40           45        20                1
1  Bangalore      50           30        10                1
2    Ecuador      10           20        70                0
3          a      60           45        70                1
4  Bangalore      30           48        10                1

In [7]:
data.describe()

          Oxygen  Temperature    Humidity  Fire Occurrence
count  39.000000    39.000000   39.000000        39.000000
mean   33.846154    33.794872   36.282051         0.512821
std    23.734872    16.225677   28.046905         0.506370
min     0.000000     0.000000    0.000000         0.000000
25%    11.500000    20.000000   13.500000         0.000000
50%    30.000000    35.000000   30.000000         1.000000
75%    50.000000    45.000000   62.500000         1.000000
max    89.000000    60.000000  100.000000         1.000000

In [8]:
data.isnull().sum()

Area               10
Oxygen              0
Temperature         0
Humidity            0
Fire Occurrence     0
dtype: int64

In [9]:
data.columns

Index(['Area', 'Oxygen', 'Temperature', 'Humidity', 'Fire Occurrence'], dtype='object')

In [10]:
data.shape

(39, 5)

In [11]:
data.head()

        Area  Oxygen  Temperature  Humidity  Fire Occurrence
0   Jharkand      40           45        20                1
1  Bangalore      50           30        10                1
2    Ecuador      10           20        70                0
3          a      60           45        70                1
4  Bangalore      30           48        10                1

In [ ]:
data.drop('Area',axis=1,inplace=True)

In [ ]:
x = data.drop('Fire Occurrence',axis=1)
y = data['Fire Occurrence']

In [ ]:
print(x.shape)
print(y.shape)

(39, 3)
(39,)

In [ ]:
x.head()

   Oxygen  Temperature  Humidity
0      40           45        20
1      50           30        10
2      10           20        70
3      60           45        70
4      30           48        10

In [ ]:
y.head()

0    1
1    1
2    0
3    1
4    1
Name: Fire Occurrence, dtype: int64

# traintest split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(31, 3)
(8, 3)
(31,)
(8,)

#Processing

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
scaler=Normalizer().fit(x_train)
normalizer_x_train=scaler.transform(x_train)
normalizer_x_test=scaler.transform(x_test)

#Apply Algorithm

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

LogisticRegression()

#checking Accuracy Traning

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
x_train_pre = model.predict(x_train)

training_data_accuracy = accuracy_score(x_train_pre,y_train)

In [ ]:
training_data_accuracy

1.0

#save pickle file

In [ ]:
import pickle

In [ ]:
file = 'one.pkl'

In [ ]:
pickle.dump(model,open(file,'wb'))

#Loading the file

In [ ]:
one = pickle.load(open('one.pkl','rb'))

In [ ]:
one

LogisticRegression()

#output

In [ ]:
data.head()

   Oxygen  Temperature  Humidity  Fire Occurrence
0      40           45        20                1
1      50           30        10                1
2      10           20        70                0
3      60           45        70                1
4      30           48        10                1

In [ ]:
input_data = (50,30,10)

input_np = np.asarray(input_data)

reshape = input_np.reshape(1,-1)

prediction = one.predict(reshape)
print(prediction)

if (prediction[0] == 0):
  print('No Fire')
else:
  print('Fire')

[1]
Fire

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(